version: '3.1'
services:

postgres:
 image: postgres:latest
 ports:
  - "8020:5432"
 networks: postgres
 volumes:
  - /data/postgres:/data/postgres
 hostname: postgres
environment:
 POSTGRES_USER: postgres
 POSTGRES_PASSWORD: 123456
PGDATA: /data/postgres
restart: always


pgadmin:
 image: dpage/pgadmin4:latest
 volumes:
  - /data/pgadmin:/root/.pgadmin
 ports:
  - "5050:80"
environment:
 PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
 PGADMIN_DEFAULT_PASSWORD: 123456

restart: always