version: '3.1'

services:
postgres:
image: postgres:latest
hostname: postgres
environment:
POSTGRES_USER: postgres
POSTGRES_PASSWORD: 123456
PGDATA: /data/postgres
volumes:
- /data/postgres:/data/postgres
restart: always
ports:
- "8020:5432"

pgadmin:
image: dpage/pgadmin4:latest
depends_on:
- postgres
environment:
PGADMIN_DEFAULT_EMAIL: pgadmin@mail.com
PGADMIN_DEFAULT_PASSWORD: 123456
volumes:
- /data/pgadmin:/root/.pgadmin
ports:
- "5050:80"
restart: always